meta_product_name: "HostIt"
meta_title: "HostIt - Bring your friends together!"
meta_description: "HostIt is the event planner all of us always wanted. Designed to make the task of organizing house-parties, movie-nights, BBQ afternoons and sleepovers more fun and hustle-free. "
meta_image: "meta-banner.png" 